version: "3.9"
services:
  db:
    image: postgres:13.5
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sbertravel
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    expose:
      - "5432"
  redis:
    image: library/redis:latest
    ports:
      - "6388:6379"
  
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: elastic
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq

volumes:
  elastic:

networks:
  default:
    external:
      name: goroomagent_default
